package com.thelegacycoder.livecolorpicker;

import android.os.Bundle;
import android.support.v4.graphics.ColorUtils;
import android.support.v7.app.AppCompatActivity;

import java.util.ArrayList;
import java.util.LinkedHashMap;

public class MainActivity extends AppCompatActivity {


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        createDictionary();


        getColorName("#rrggbb");
    }

    LinkedHashMap<String, String> colorDictionary = new LinkedHashMap<>();
    ArrayList<String> colors = new ArrayList<>();

    private String getColorName(String color) {
        double ndf1 = 0;
        double ndf2 = 0;
        double ndf = 0;
        int cl = -1;
        double df = -1;
        float[] hsvColor = new float[3];
        ColorUtils.RGBToHSL(getR(color), getG(color), getB(color), hsvColor);
        for (int i = 0; i < colorDictionary.size(); i++) {
            if (color.equalsIgnoreCase(colorDictionary.get(color)))
                return colorDictionary.get(color);
            else {
                float[] hsvIterationColor = new float[3];
                ColorUtils.RGBToHSL(getR(colors.get(i)), getG(colors.get(i)), getB(colors.get(i)), hsvIterationColor);
                ndf1 = Math.pow(getR(color) - getR(colors.get(i)), 2) + Math.pow(getG(color) - getG(colors.get(i)), 2) + Math.pow(getB(color) - getB(colors.get(i)), 2);
                ndf2 = Math.pow(hsvColor[0] - hsvIterationColor[0], 2) + Math.pow(hsvColor[1] - hsvIterationColor[1], 2) + Math.pow(hsvColor[2] - hsvIterationColor[2], 2);

                ndf = ndf1 + ndf2 * 2;
                if (df < 0 || df > ndf) {
                    df = ndf;
                    cl = i;
                }
            }
        }
        return cl < 0 ? ("Invalid Color: " + color) : colorDictionary.get(colors.get(cl));//[cl][1];
    }

    private int getR(String color) {
        return Integer.valueOf(color.substring(1, 3), 16);
    }

    private int getG(String color) {
        return Integer.valueOf(color.substring(3, 5), 16);
    }

    private int getB(String color) {
        return Integer.valueOf(color.substring(5, 7), 16);
    }

    private void createDictionary() {
        colorDictionary.put("#000000", "Black");
        colorDictionary.put("#000080", "Navy Blue");
        colorDictionary.put("#0000C8", "Dark Blue");
        colorDictionary.put("#0000FF", "Blue");
        colorDictionary.put("#000741", "Stratos");
        colorDictionary.put("#001B1C", "Swamp");
        colorDictionary.put("#002387", "Resolution Blue");
        colorDictionary.put("#002900", "Deep Fir");
        colorDictionary.put("#002E20", "Burnham");
        colorDictionary.put("#002FA7", "International Klein Blue");
        colorDictionary.put("#003153", "Prussian Blue");
        colorDictionary.put("#003366", "Midnight Blue");
        colorDictionary.put("#003399", "Smalt");
        colorDictionary.put("#003532", "Deep Teal");
        colorDictionary.put("#003E40", "Cyprus");
        colorDictionary.put("#004620", "Kaitoke Green");
        colorDictionary.put("#0047AB", "Cobalt");
        colorDictionary.put("#004816", "Crusoe");
        colorDictionary.put("#004950", "Sherpa Blue");
        colorDictionary.put("#0056A7", "Endeavour");
        colorDictionary.put("#00581A", "Camarone");
        colorDictionary.put("#0066CC", "Science Blue");
        colorDictionary.put("#0066FF", "Blue Ribbon");
        colorDictionary.put("#00755E", "Tropical Rain Forest");
        colorDictionary.put("#0076A3", "Allports");
        colorDictionary.put("#007BA7", "Deep Cerulean");
        colorDictionary.put("#007EC7", "Lochmara");
        colorDictionary.put("#007FFF", "Azure Radiance");
        colorDictionary.put("#008080", "Teal");
        colorDictionary.put("#0095B6", "Bondi Blue");
        colorDictionary.put("#009DC4", "Pacific Blue");
        colorDictionary.put("#00A693", "Persian Green");
        colorDictionary.put("#00A86B", "Jade");
        colorDictionary.put("#00CC99", "Caribbean Green");
        colorDictionary.put("#00CCCC", "Robin's Egg Blue");
        colorDictionary.put("#00FF00", "Green");
        colorDictionary.put("#00FF7F", "Spring Green");
        colorDictionary.put("#00FFFF", "Cyan / Aqua");
        colorDictionary.put("#010D1A", "Blue Charcoal");
        colorDictionary.put("#011635", "Midnight");
        colorDictionary.put("#011D13", "Holly");
        colorDictionary.put("#012731", "Daintree");
        colorDictionary.put("#01361C", "Cardin Green");
        colorDictionary.put("#01371A", "County Green");
        colorDictionary.put("#013E62", "Astronaut Blue");
        colorDictionary.put("#013F6A", "Regal Blue");
        colorDictionary.put("#014B43", "Aqua Deep");
        colorDictionary.put("#015E85", "Orient");
        colorDictionary.put("#016162", "Blue Stone");
        colorDictionary.put("#016D39", "Fun Green");
        colorDictionary.put("#01796F", "Pine Green");
        colorDictionary.put("#017987", "Blue Lagoon");
        colorDictionary.put("#01826B", "Deep Sea");
        colorDictionary.put("#01A368", "Green Haze");
        colorDictionary.put("#022D15", "English Holly");
        colorDictionary.put("#02402C", "Sherwood Green");
        colorDictionary.put("#02478E", "Congress Blue");
        colorDictionary.put("#024E46", "Evening Sea");
        colorDictionary.put("#026395", "Bahama Blue");
        colorDictionary.put("#02866F", "Observatory");
        colorDictionary.put("#02A4D3", "Cerulean");
        colorDictionary.put("#03163C", "Tangaroa");
        colorDictionary.put("#032B52", "Green Vogue");
        colorDictionary.put("#036A6E", "Mosque");
        colorDictionary.put("#041004", "Midnight Moss");
        colorDictionary.put("#041322", "Black Pearl");
        colorDictionary.put("#042E4C", "Blue Whale");
        colorDictionary.put("#044022", "Zuccini");
        colorDictionary.put("#044259", "Teal Blue");
        colorDictionary.put("#051040", "Deep Cove");
        colorDictionary.put("#051657", "Gulf Blue");
        colorDictionary.put("#055989", "Venice Blue");
        colorDictionary.put("#056F57", "Watercourse");
        colorDictionary.put("#062A78", "Catalina Blue");
        colorDictionary.put("#063537", "Tiber");
        colorDictionary.put("#069B81", "Gossamer");
        colorDictionary.put("#06A189", "Niagara");
        colorDictionary.put("#073A50", "Tarawera");
        colorDictionary.put("#080110", "Jaguar");
        colorDictionary.put("#081910", "Black Bean");
        colorDictionary.put("#082567", "Deep Sapphire");
        colorDictionary.put("#088370", "Elf Green");
        colorDictionary.put("#08E8DE", "Bright Turquoise");
        colorDictionary.put("#092256", "Downriver");
        colorDictionary.put("#09230F", "Palm Green");
        colorDictionary.put("#09255D", "Madison");
        colorDictionary.put("#093624", "Bottle Green");
        colorDictionary.put("#095859", "Deep Sea Green");
        colorDictionary.put("#097F4B", "Salem");
        colorDictionary.put("#0A001C", "Black Russian");
        colorDictionary.put("#0A480D", "Dark Fern");
        colorDictionary.put("#0A6906", "Japanese Laurel");
        colorDictionary.put("#0A6F75", "Atoll");
        colorDictionary.put("#0B0B0B", "Cod Gray");
        colorDictionary.put("#0B0F08", "Marshland");
        colorDictionary.put("#0B1107", "Gordons Green");
        colorDictionary.put("#0B1304", "Black Forest");
        colorDictionary.put("#0B6207", "San Felix");
        colorDictionary.put("#0BDA51", "Malachite");
        colorDictionary.put("#0C0B1D", "Ebony");
        colorDictionary.put("#0C0D0F", "Woodsmoke");
        colorDictionary.put("#0C1911", "Racing Green");
        colorDictionary.put("#0C7A79", "Surfie Green");
        colorDictionary.put("#0C8990", "Blue Chill");
        colorDictionary.put("#0D0332", "Black Rock");
        colorDictionary.put("#0D1117", "Bunker");
        colorDictionary.put("#0D1C19", "Aztec");
        colorDictionary.put("#0D2E1C", "Bush");
        colorDictionary.put("#0E0E18", "Cinder");
        colorDictionary.put("#0E2A30", "Firefly");
        colorDictionary.put("#0F2D9E", "Torea Bay");
        colorDictionary.put("#10121D", "Vulcan");
        colorDictionary.put("#101405", "Green Waterloo");
        colorDictionary.put("#105852", "Eden");
        colorDictionary.put("#110C6C", "Arapawa");
        colorDictionary.put("#120A8F", "Ultramarine");
        colorDictionary.put("#123447", "Elephant");
        colorDictionary.put("#126B40", "Jewel");
        colorDictionary.put("#130000", "Diesel");
        colorDictionary.put("#130A06", "Asphalt");
        colorDictionary.put("#13264D", "Blue Zodiac");
        colorDictionary.put("#134F19", "Parsley");
        colorDictionary.put("#140600", "Nero");
        colorDictionary.put("#1450AA", "Tory Blue");
        colorDictionary.put("#151F4C", "Bunting");
        colorDictionary.put("#1560BD", "Denim");
        colorDictionary.put("#15736B", "Genoa");
        colorDictionary.put("#161928", "Mirage");
        colorDictionary.put("#161D10", "Hunter Green");
        colorDictionary.put("#162A40", "Big Stone");
        colorDictionary.put("#163222", "Celtic");
        colorDictionary.put("#16322C", "Timber Green");
        colorDictionary.put("#163531", "Gable Green");
        colorDictionary.put("#171F04", "Pine Tree");
        colorDictionary.put("#175579", "Chathams Blue");
        colorDictionary.put("#182D09", "Deep Forest Green");
        colorDictionary.put("#18587A", "Blumine");
        colorDictionary.put("#19330E", "Palm Leaf");
        colorDictionary.put("#193751", "Nile Blue");
        colorDictionary.put("#1959A8", "Fun Blue");
        colorDictionary.put("#1A1A68", "Lucky Point");
        colorDictionary.put("#1AB385", "Mountain Meadow");
        colorDictionary.put("#1B0245", "Tolopea");
        colorDictionary.put("#1B1035", "Haiti");
        colorDictionary.put("#1B127B", "Deep Koamaru");
        colorDictionary.put("#1B1404", "Acadia");
        colorDictionary.put("#1B2F11", "Seaweed");
        colorDictionary.put("#1B3162", "Biscay");
        colorDictionary.put("#1B659D", "Matisse");
        colorDictionary.put("#1C1208", "Crowshead");
        colorDictionary.put("#1C1E13", "Rangoon Green");
        colorDictionary.put("#1C39BB", "Persian Blue");
        colorDictionary.put("#1C402E", "Everglade");
        colorDictionary.put("#1C7C7D", "Elm");
        colorDictionary.put("#1D6142", "Green Pea");
        colorDictionary.put("#1E0F04", "Creole");
        colorDictionary.put("#1E1609", "Karaka");
        colorDictionary.put("#1E1708", "El Paso");
        colorDictionary.put("#1E385B", "Cello");
        colorDictionary.put("#1E433C", "Te Papa Green");
        colorDictionary.put("#1E90FF", "Dodger Blue");
        colorDictionary.put("#1E9AB0", "Eastern Blue");
        colorDictionary.put("#1F120F", "Night Rider");
        colorDictionary.put("#1FC2C2", "Java");
        colorDictionary.put("#20208D", "Jacksons Purple");
        colorDictionary.put("#202E54", "Cloud Burst");
        colorDictionary.put("#204852", "Blue Dianne");
        colorDictionary.put("#211A0E", "Eternity");
        colorDictionary.put("#220878", "Deep Blue");
        colorDictionary.put("#228B22", "Forest Green");
        colorDictionary.put("#233418", "Mallard");
        colorDictionary.put("#240A40", "Violet");
        colorDictionary.put("#240C02", "Kilamanjaro");
        colorDictionary.put("#242A1D", "Log Cabin");
        colorDictionary.put("#242E16", "Black Olive");
        colorDictionary.put("#24500F", "Green House");
        colorDictionary.put("#251607", "Graphite");
        colorDictionary.put("#251706", "Cannon Black");
        colorDictionary.put("#251F4F", "Port Gore");
        colorDictionary.put("#25272C", "Shark");
        colorDictionary.put("#25311C", "Green Kelp");
        colorDictionary.put("#2596D1", "Curious Blue");
        colorDictionary.put("#260368", "Paua");
        colorDictionary.put("#26056A", "Paris M");
        colorDictionary.put("#261105", "Wood Bark");
        colorDictionary.put("#261414", "Gondola");
        colorDictionary.put("#262335", "Steel Gray");
        colorDictionary.put("#26283B", "Ebony Clay");
        colorDictionary.put("#273A81", "Bay of Many");
        colorDictionary.put("#27504B", "Plantation");
        colorDictionary.put("#278A5B", "Eucalyptus");
        colorDictionary.put("#281E15", "Oil");
        colorDictionary.put("#283A77", "Astronaut");
        colorDictionary.put("#286ACD", "Mariner");
        colorDictionary.put("#290C5E", "Violent Violet");
        colorDictionary.put("#292130", "Bastille");
        colorDictionary.put("#292319", "Zeus");
        colorDictionary.put("#292937", "Charade");
        colorDictionary.put("#297B9A", "Jelly Bean");
        colorDictionary.put("#29AB87", "Jungle Green");
        colorDictionary.put("#2A0359", "Cherry Pie");
        colorDictionary.put("#2A140E", "Coffee Bean");
        colorDictionary.put("#2A2630", "Baltic Sea");
        colorDictionary.put("#2A380B", "Turtle Green");
        colorDictionary.put("#2A52BE", "Cerulean Blue");
        colorDictionary.put("#2B0202", "Sepia Black");
        colorDictionary.put("#2B194F", "Valhalla");
        colorDictionary.put("#2B3228", "Heavy Metal");
        colorDictionary.put("#2C0E8C", "Blue Gem");
        colorDictionary.put("#2C1632", "Revolver");
        colorDictionary.put("#2C2133", "Bleached Cedar");
        colorDictionary.put("#2C8C84", "Lochinvar");
        colorDictionary.put("#2D2510", "Mikado");
        colorDictionary.put("#2D383A", "Outer Space");
        colorDictionary.put("#2D569B", "St Tropaz");
        colorDictionary.put("#2E0329", "Jacaranda");
        colorDictionary.put("#2E1905", "Jacko Bean");
        colorDictionary.put("#2E3222", "Rangitoto");
        colorDictionary.put("#2E3F62", "Rhino");
        colorDictionary.put("#2E8B57", "Sea Green");
        colorDictionary.put("#2EBFD4", "Scooter");
        colorDictionary.put("#2F270E", "Onion");
        colorDictionary.put("#2F3CB3", "Governor Bay");
        colorDictionary.put("#2F519E", "Sapphire");
        colorDictionary.put("#2F5A57", "Spectra");
        colorDictionary.put("#2F6168", "Casal");
        colorDictionary.put("#300529", "Melanzane");
        colorDictionary.put("#301F1E", "Cocoa Brown");
        colorDictionary.put("#302A0F", "Woodrush");
        colorDictionary.put("#304B6A", "San Juan");
        colorDictionary.put("#30D5C8", "Turquoise");
        colorDictionary.put("#311C17", "Eclipse");
        colorDictionary.put("#314459", "Pickled Bluewood");
        colorDictionary.put("#315BA1", "Azure");
        colorDictionary.put("#31728D", "Calypso");
        colorDictionary.put("#317D82", "Paradiso");
        colorDictionary.put("#32127A", "Persian Indigo");
        colorDictionary.put("#32293A", "Blackcurrant");
        colorDictionary.put("#323232", "Mine Shaft");
        colorDictionary.put("#325D52", "Stromboli");
        colorDictionary.put("#327C14", "Bilbao");
        colorDictionary.put("#327DA0", "Astral");
        colorDictionary.put("#33036B", "Christalle");
        colorDictionary.put("#33292F", "Thunder");
        colorDictionary.put("#33CC99", "Shamrock");
        colorDictionary.put("#341515", "Tamarind");
        colorDictionary.put("#350036", "Mardi Gras");
        colorDictionary.put("#350E42", "Valentino");
        colorDictionary.put("#350E57", "Jagger");
        colorDictionary.put("#353542", "Tuna");
        colorDictionary.put("#354E8C", "Chambray");
        colorDictionary.put("#363050", "Martinique");
        colorDictionary.put("#363534", "Tuatara");
        colorDictionary.put("#363C0D", "Waiouru");
        colorDictionary.put("#36747D", "Ming");
        colorDictionary.put("#368716", "La Palma");
        colorDictionary.put("#370202", "Chocolate");
        colorDictionary.put("#371D09", "Clinker");
        colorDictionary.put("#37290E", "Brown Tumbleweed");
        colorDictionary.put("#373021", "Birch");
        colorDictionary.put("#377475", "Oracle");
        colorDictionary.put("#380474", "Blue Diamond");
        colorDictionary.put("#381A51", "Grape");
        colorDictionary.put("#383533", "Dune");
        colorDictionary.put("#384555", "Oxford Blue");
        colorDictionary.put("#384910", "Clover");
        colorDictionary.put("#394851", "Limed Spruce");
        colorDictionary.put("#396413", "Dell");
        colorDictionary.put("#3A0020", "Toledo");
        colorDictionary.put("#3A2010", "Sambuca");
        colorDictionary.put("#3A2A6A", "Jacarta");
        colorDictionary.put("#3A686C", "William");
        colorDictionary.put("#3A6A47", "Killarney");
        colorDictionary.put("#3AB09E", "Keppel");
        colorDictionary.put("#3B000B", "Temptress");
        colorDictionary.put("#3B0910", "Aubergine");
        colorDictionary.put("#3B1F1F", "Jon");
        colorDictionary.put("#3B2820", "Treehouse");
        colorDictionary.put("#3B7A57", "Amazon");
        colorDictionary.put("#3B91B4", "Boston Blue");
        colorDictionary.put("#3C0878", "Windsor");
        colorDictionary.put("#3C1206", "Rebel");
        colorDictionary.put("#3C1F76", "Meteorite");
        colorDictionary.put("#3C2005", "Dark Ebony");
        colorDictionary.put("#3C3910", "Camouflage");
        colorDictionary.put("#3C4151", "Bright Gray");
        colorDictionary.put("#3C4443", "Cape Cod");
        colorDictionary.put("#3C493A", "Lunar Green");
        colorDictionary.put("#3D0C02", "Bean  ");
        colorDictionary.put("#3D2B1F", "Bistre");
        colorDictionary.put("#3D7D52", "Goblin");
        colorDictionary.put("#3E0480", "Kingfisher Daisy");
        colorDictionary.put("#3E1C14", "Cedar");
        colorDictionary.put("#3E2B23", "English Walnut");
        colorDictionary.put("#3E2C1C", "Black Marlin");
        colorDictionary.put("#3E3A44", "Ship Gray");
        colorDictionary.put("#3EABBF", "Pelorous");
        colorDictionary.put("#3F2109", "Bronze");
        colorDictionary.put("#3F2500", "Cola");
        colorDictionary.put("#3F3002", "Madras");
        colorDictionary.put("#3F307F", "Minsk");
        colorDictionary.put("#3F4C3A", "Cabbage Pont");
        colorDictionary.put("#3F583B", "Tom Thumb");
        colorDictionary.put("#3F5D53", "Mineral Green");
        colorDictionary.put("#3FC1AA", "Puerto Rico");
        colorDictionary.put("#3FFF00", "Harlequin");
        colorDictionary.put("#401801", "Brown Pod");
        colorDictionary.put("#40291D", "Cork");
        colorDictionary.put("#403B38", "Masala");
        colorDictionary.put("#403D19", "Thatch Green");
        colorDictionary.put("#405169", "Fiord");
        colorDictionary.put("#40826D", "Viridian");
        colorDictionary.put("#40A860", "Chateau Green");
        colorDictionary.put("#410056", "Ripe Plum");
        colorDictionary.put("#411F10", "Paco");
        colorDictionary.put("#412010", "Deep Oak");
        colorDictionary.put("#413C37", "Merlin");
        colorDictionary.put("#414257", "Gun Powder");
        colorDictionary.put("#414C7D", "East Bay");
        colorDictionary.put("#4169E1", "Royal Blue");
        colorDictionary.put("#41AA78", "Ocean Green");
        colorDictionary.put("#420303", "Burnt Maroon");
        colorDictionary.put("#423921", "Lisbon Brown");
        colorDictionary.put("#427977", "Faded Jade");
        colorDictionary.put("#431560", "Scarlet Gum");
        colorDictionary.put("#433120", "Iroko");
        colorDictionary.put("#433E37", "Armadillo");
        colorDictionary.put("#434C59", "River Bed");
        colorDictionary.put("#436A0D", "Green Leaf");
        colorDictionary.put("#44012D", "Barossa");
        colorDictionary.put("#441D00", "Morocco Brown");
        colorDictionary.put("#444954", "Mako");
        colorDictionary.put("#454936", "Kelp");
        colorDictionary.put("#456CAC", "San Marino");
        colorDictionary.put("#45B1E8", "Picton Blue");
        colorDictionary.put("#460B41", "Loulou");
        colorDictionary.put("#462425", "Crater Brown");
        colorDictionary.put("#465945", "Gray Asparagus");
        colorDictionary.put("#4682B4", "Steel Blue");
        colorDictionary.put("#480404", "Rustic Red");
        colorDictionary.put("#480607", "Bulgarian Rose");
        colorDictionary.put("#480656", "Clairvoyant");
        colorDictionary.put("#481C1C", "Cocoa Bean");
        colorDictionary.put("#483131", "Woody Brown");
        colorDictionary.put("#483C32", "Taupe");
        colorDictionary.put("#49170C", "Van Cleef");
        colorDictionary.put("#492615", "Brown Derby");
        colorDictionary.put("#49371B", "Metallic Bronze");
        colorDictionary.put("#495400", "Verdun Green");
        colorDictionary.put("#496679", "Blue Bayoux");
        colorDictionary.put("#497183", "Bismark");
        colorDictionary.put("#4A2A04", "Bracken");
        colorDictionary.put("#4A3004", "Deep Bronze");
        colorDictionary.put("#4A3C30", "Mondo");
        colorDictionary.put("#4A4244", "Tundora");
        colorDictionary.put("#4A444B", "Gravel");
        colorDictionary.put("#4A4E5A", "Trout");
        colorDictionary.put("#4B0082", "Pigment Indigo");
        colorDictionary.put("#4B5D52", "Nandor");
        colorDictionary.put("#4C3024", "Saddle");
        colorDictionary.put("#4C4F56", "Abbey");
        colorDictionary.put("#4D0135", "Blackberry");
        colorDictionary.put("#4D0A18", "Cab Sav");
        colorDictionary.put("#4D1E01", "Indian Tan");
        colorDictionary.put("#4D282D", "Cowboy");
        colorDictionary.put("#4D282E", "Livid Brown");
        colorDictionary.put("#4D3833", "Rock");
        colorDictionary.put("#4D3D14", "Punga");
        colorDictionary.put("#4D400F", "Bronzetone");
        colorDictionary.put("#4D5328", "Woodland");
        colorDictionary.put("#4E0606", "Mahogany");
        colorDictionary.put("#4E2A5A", "Bossanova");
        colorDictionary.put("#4E3B41", "Matterhorn");
        colorDictionary.put("#4E420C", "Bronze Olive");
        colorDictionary.put("#4E4562", "Mulled Wine");
        colorDictionary.put("#4E6649", "Axolotl");
        colorDictionary.put("#4E7F9E", "Wedgewood");
        colorDictionary.put("#4EABD1", "Shakespeare");
        colorDictionary.put("#4F1C70", "Honey Flower");
        colorDictionary.put("#4F2398", "Daisy Bush");
        colorDictionary.put("#4F69C6", "Indigo");
        colorDictionary.put("#4F7942", "Fern Green");
        colorDictionary.put("#4F9D5D", "Fruit Salad");
        colorDictionary.put("#4FA83D", "Apple");
        colorDictionary.put("#504351", "Mortar");
        colorDictionary.put("#507096", "Kashmir Blue");
        colorDictionary.put("#507672", "Cutty Sark");
        colorDictionary.put("#50C878", "Emerald");
        colorDictionary.put("#514649", "Emperor");
        colorDictionary.put("#516E3D", "Chalet Green");
        colorDictionary.put("#517C66", "Como");
        colorDictionary.put("#51808F", "Smalt Blue");
        colorDictionary.put("#52001F", "Castro");
        colorDictionary.put("#520C17", "Maroon Oak");
        colorDictionary.put("#523C94", "Gigas");
        colorDictionary.put("#533455", "Voodoo");
        colorDictionary.put("#534491", "Victoria");
        colorDictionary.put("#53824B", "Hippie Green");
        colorDictionary.put("#541012", "Heath");
        colorDictionary.put("#544333", "Judge Gray");
        colorDictionary.put("#54534D", "Fuscous Gray");
        colorDictionary.put("#549019", "Vida Loca");
        colorDictionary.put("#55280C", "Cioccolato");
        colorDictionary.put("#555B10", "Saratoga");
        colorDictionary.put("#556D56", "Finlandia");
        colorDictionary.put("#5590D9", "Havelock Blue");
        colorDictionary.put("#56B4BE", "Fountain Blue");
        colorDictionary.put("#578363", "Spring Leaves");
        colorDictionary.put("#583401", "Saddle Brown");
        colorDictionary.put("#585562", "Scarpa Flow");
        colorDictionary.put("#587156", "Cactus");
        colorDictionary.put("#589AAF", "Hippie Blue");
        colorDictionary.put("#591D35", "Wine Berry");
        colorDictionary.put("#592804", "Brown Bramble");
        colorDictionary.put("#593737", "Congo Brown");
        colorDictionary.put("#594433", "Millbrook");
        colorDictionary.put("#5A6E9C", "Waikawa Gray");
        colorDictionary.put("#5A87A0", "Horizon");
        colorDictionary.put("#5B3013", "Jambalaya");
        colorDictionary.put("#5C0120", "Bordeaux");
        colorDictionary.put("#5C0536", "Mulberry Wood");
        colorDictionary.put("#5C2E01", "Carnaby Tan");
        colorDictionary.put("#5C5D75", "Comet");
        colorDictionary.put("#5D1E0F", "Redwood");
        colorDictionary.put("#5D4C51", "Don Juan");
        colorDictionary.put("#5D5C58", "Chicago");
        colorDictionary.put("#5D5E37", "Verdigris");
        colorDictionary.put("#5D7747", "Dingley");
        colorDictionary.put("#5DA19F", "Breaker Bay");
        colorDictionary.put("#5E483E", "Kabul");
        colorDictionary.put("#5E5D3B", "Hemlock");
        colorDictionary.put("#5F3D26", "Irish Coffee");
        colorDictionary.put("#5F5F6E", "Mid Gray");
        colorDictionary.put("#5F6672", "Shuttle Gray");
        colorDictionary.put("#5FA777", "Aqua Forest");
        colorDictionary.put("#5FB3AC", "Tradewind");
        colorDictionary.put("#604913", "Horses Neck");
        colorDictionary.put("#605B73", "Smoky");
        colorDictionary.put("#606E68", "Corduroy");
        colorDictionary.put("#6093D1", "Danube");
        colorDictionary.put("#612718", "Espresso");
        colorDictionary.put("#614051", "Eggplant");
        colorDictionary.put("#615D30", "Costa Del Sol");
        colorDictionary.put("#61845F", "Glade Green");
        colorDictionary.put("#622F30", "Buccaneer");
        colorDictionary.put("#623F2D", "Quincy");
        colorDictionary.put("#624E9A", "Butterfly Bush");
        colorDictionary.put("#625119", "West Coast");
        colorDictionary.put("#626649", "Finch");
        colorDictionary.put("#639A8F", "Patina");
        colorDictionary.put("#63B76C", "Fern");
        colorDictionary.put("#6456B7", "Blue Violet");
        colorDictionary.put("#646077", "Dolphin");
        colorDictionary.put("#646463", "Storm Dust");
        colorDictionary.put("#646A54", "Siam");
        colorDictionary.put("#646E75", "Nevada");
        colorDictionary.put("#6495ED", "Cornflower Blue");
        colorDictionary.put("#64CCDB", "Viking");
        colorDictionary.put("#65000B", "Rosewood");
        colorDictionary.put("#651A14", "Cherrywood");
        colorDictionary.put("#652DC1", "Purple Heart");
        colorDictionary.put("#657220", "Fern Frond");
        colorDictionary.put("#65745D", "Willow Grove");
        colorDictionary.put("#65869F", "Hoki");
        colorDictionary.put("#660045", "Pompadour");
        colorDictionary.put("#660099", "Purple");
        colorDictionary.put("#66023C", "Tyrian Purple");
        colorDictionary.put("#661010", "Dark Tan");
        colorDictionary.put("#66B58F", "Silver Tree");
        colorDictionary.put("#66FF00", "Bright Green");
        colorDictionary.put("#66FF66", "Screamin' Green");
        colorDictionary.put("#67032D", "Black Rose");
        colorDictionary.put("#675FA6", "Scampi");
        colorDictionary.put("#676662", "Ironside Gray");
        colorDictionary.put("#678975", "Viridian Green");
        colorDictionary.put("#67A712", "Christi");
        colorDictionary.put("#683600", "Nutmeg Wood Finish");
        colorDictionary.put("#685558", "Zambezi");
        colorDictionary.put("#685E6E", "Salt Box");
        colorDictionary.put("#692545", "Tawny Port");
        colorDictionary.put("#692D54", "Finn");
        colorDictionary.put("#695F62", "Scorpion");
        colorDictionary.put("#697E9A", "Lynch");
        colorDictionary.put("#6A442E", "Spice");
        colorDictionary.put("#6A5D1B", "Himalaya");
        colorDictionary.put("#6A6051", "Soya Bean");
        colorDictionary.put("#6B2A14", "Hairy Heath");
        colorDictionary.put("#6B3FA0", "Royal Purple");
        colorDictionary.put("#6B4E31", "Shingle Fawn");
        colorDictionary.put("#6B5755", "Dorado");
        colorDictionary.put("#6B8BA2", "Bermuda Gray");
        colorDictionary.put("#6B8E23", "Olive Drab");
        colorDictionary.put("#6C3082", "Eminence");
        colorDictionary.put("#6CDAE7", "Turquoise Blue");
        colorDictionary.put("#6D0101", "Lonestar");
        colorDictionary.put("#6D5E54", "Pine Cone");
        colorDictionary.put("#6D6C6C", "Dove Gray");
        colorDictionary.put("#6D9292", "Juniper");
        colorDictionary.put("#6D92A1", "Gothic");
        colorDictionary.put("#6E0902", "Red Oxide");
        colorDictionary.put("#6E1D14", "Moccaccino");
        colorDictionary.put("#6E4826", "Pickled Bean");
        colorDictionary.put("#6E4B26", "Dallas");
        colorDictionary.put("#6E6D57", "Kokoda");
        colorDictionary.put("#6E7783", "Pale Sky");
        colorDictionary.put("#6F440C", "Cafe Royale");
        colorDictionary.put("#6F6A61", "Flint");
        colorDictionary.put("#6F8E63", "Highland");
        colorDictionary.put("#6F9D02", "Limeade");
        colorDictionary.put("#6FD0C5", "Downy");
        colorDictionary.put("#701C1C", "Persian Plum");
        colorDictionary.put("#704214", "Sepia");
        colorDictionary.put("#704A07", "Antique Bronze");
        colorDictionary.put("#704F50", "Ferra");
        colorDictionary.put("#706555", "Coffee");
        colorDictionary.put("#708090", "Slate Gray");
        colorDictionary.put("#711A00", "Cedar Wood Finish");
        colorDictionary.put("#71291D", "Metallic Copper");
        colorDictionary.put("#714693", "Affair");
        colorDictionary.put("#714AB2", "Studio");
        colorDictionary.put("#715D47", "Tobacco Brown");
        colorDictionary.put("#716338", "Yellow Metal");
        colorDictionary.put("#716B56", "Peat");
        colorDictionary.put("#716E10", "Olivetone");
        colorDictionary.put("#717486", "Storm Gray");
        colorDictionary.put("#718080", "Sirocco");
        colorDictionary.put("#71D9E2", "Aquamarine Blue");
        colorDictionary.put("#72010F", "Venetian Red");
        colorDictionary.put("#724A2F", "Old Copper");
        colorDictionary.put("#726D4E", "Go Ben");
        colorDictionary.put("#727B89", "Raven");
        colorDictionary.put("#731E8F", "Seance");
        colorDictionary.put("#734A12", "Raw Umber");
        colorDictionary.put("#736C9F", "Kimberly");
        colorDictionary.put("#736D58", "Crocodile");
        colorDictionary.put("#737829", "Crete");
        colorDictionary.put("#738678", "Xanadu");
        colorDictionary.put("#74640D", "Spicy Mustard");
        colorDictionary.put("#747D63", "Limed Ash");
        colorDictionary.put("#747D83", "Rolling Stone");
        colorDictionary.put("#748881", "Blue Smoke");
        colorDictionary.put("#749378", "Laurel");
        colorDictionary.put("#74C365", "Mantis");
        colorDictionary.put("#755A57", "Russett");
        colorDictionary.put("#7563A8", "Deluge");
        colorDictionary.put("#76395D", "Cosmic");
        colorDictionary.put("#7666C6", "Blue Marguerite");
        colorDictionary.put("#76BD17", "Lima");
        colorDictionary.put("#76D7EA", "Sky Blue");
        colorDictionary.put("#770F05", "Dark Burgundy");
        colorDictionary.put("#771F1F", "Crown of Thorns");
        colorDictionary.put("#773F1A", "Walnut");
        colorDictionary.put("#776F61", "Pablo");
        colorDictionary.put("#778120", "Pacifika");
        colorDictionary.put("#779E86", "Oxley");
        colorDictionary.put("#77DD77", "Pastel Green");
        colorDictionary.put("#780109", "Japanese Maple");
        colorDictionary.put("#782D19", "Mocha");
        colorDictionary.put("#782F16", "Peanut");
        colorDictionary.put("#78866B", "Camouflage Green");
        colorDictionary.put("#788A25", "Wasabi");
        colorDictionary.put("#788BBA", "Ship Cove");
        colorDictionary.put("#78A39C", "Sea Nymph");
        colorDictionary.put("#795D4C", "Roman Coffee");
        colorDictionary.put("#796878", "Old Lavender");
        colorDictionary.put("#796989", "Rum");
        colorDictionary.put("#796A78", "Fedora");
        colorDictionary.put("#796D62", "Sandstone");
        colorDictionary.put("#79DEEC", "Spray");
        colorDictionary.put("#7A013A", "Siren");
        colorDictionary.put("#7A58C1", "Fuchsia Blue");
        colorDictionary.put("#7A7A7A", "Boulder");
        colorDictionary.put("#7A89B8", "Wild Blue Yonder");
        colorDictionary.put("#7AC488", "De York");
        colorDictionary.put("#7B3801", "Red Beech");
        colorDictionary.put("#7B3F00", "Cinnamon");
        colorDictionary.put("#7B6608", "Yukon Gold");
        colorDictionary.put("#7B7874", "Tapa");
        colorDictionary.put("#7B7C94", "Waterloo ");
        colorDictionary.put("#7B8265", "Flax Smoke");
        colorDictionary.put("#7B9F80", "Amulet");
        colorDictionary.put("#7BA05B", "Asparagus");
        colorDictionary.put("#7C1C05", "Kenyan Copper");
        colorDictionary.put("#7C7631", "Pesto");
        colorDictionary.put("#7C778A", "Topaz");
        colorDictionary.put("#7C7B7A", "Concord");
        colorDictionary.put("#7C7B82", "Jumbo");
        colorDictionary.put("#7C881A", "Trendy Green");
        colorDictionary.put("#7CA1A6", "Gumbo");
        colorDictionary.put("#7CB0A1", "Acapulco");
        colorDictionary.put("#7CB7BB", "Neptune");
        colorDictionary.put("#7D2C14", "Pueblo");
        colorDictionary.put("#7DA98D", "Bay Leaf");
        colorDictionary.put("#7DC8F7", "Malibu");
        colorDictionary.put("#7DD8C6", "Bermuda");
        colorDictionary.put("#7E3A15", "Copper Canyon");
        colorDictionary.put("#7F1734", "Claret");
        colorDictionary.put("#7F3A02", "Peru Tan");
        colorDictionary.put("#7F626D", "Falcon");
        colorDictionary.put("#7F7589", "Mobster");
        colorDictionary.put("#7F76D3", "Moody Blue");
        colorDictionary.put("#7FFF00", "Chartreuse");
        colorDictionary.put("#7FFFD4", "Aquamarine");
        colorDictionary.put("#800000", "Maroon");
        colorDictionary.put("#800B47", "Rose Bud Cherry");
        colorDictionary.put("#801818", "Falu Red");
        colorDictionary.put("#80341F", "Red Robin");
        colorDictionary.put("#803790", "Vivid Violet");
        colorDictionary.put("#80461B", "Russet");
        colorDictionary.put("#807E79", "Friar Gray");
        colorDictionary.put("#808000", "Olive");
        colorDictionary.put("#808080", "Gray");
        colorDictionary.put("#80B3AE", "Gulf Stream");
        colorDictionary.put("#80B3C4", "Glacier");
        colorDictionary.put("#80CCEA", "Seagull");
        colorDictionary.put("#81422C", "Nutmeg");
        colorDictionary.put("#816E71", "Spicy Pink");
        colorDictionary.put("#817377", "Empress");
        colorDictionary.put("#819885", "Spanish Green");
        colorDictionary.put("#826F65", "Sand Dune");
        colorDictionary.put("#828685", "Gunsmoke");
        colorDictionary.put("#828F72", "Battleship Gray");
        colorDictionary.put("#831923", "Merlot");
        colorDictionary.put("#837050", "Shadow");
        colorDictionary.put("#83AA5D", "Chelsea Cucumber");
        colorDictionary.put("#83D0C6", "Monte Carlo");
        colorDictionary.put("#843179", "Plum");
        colorDictionary.put("#84A0A0", "Granny Smith");
        colorDictionary.put("#8581D9", "Chetwode Blue");
        colorDictionary.put("#858470", "Bandicoot");
        colorDictionary.put("#859FAF", "Bali Hai");
        colorDictionary.put("#85C4CC", "Half Baked");
        colorDictionary.put("#860111", "Red Devil");
        colorDictionary.put("#863C3C", "Lotus");
        colorDictionary.put("#86483C", "Ironstone");
        colorDictionary.put("#864D1E", "Bull Shot");
        colorDictionary.put("#86560A", "Rusty Nail");
        colorDictionary.put("#868974", "Bitter");
        colorDictionary.put("#86949F", "Regent Gray");
        colorDictionary.put("#871550", "Disco");
        colorDictionary.put("#87756E", "Americano");
        colorDictionary.put("#877C7B", "Hurricane");
        colorDictionary.put("#878D91", "Oslo Gray");
        colorDictionary.put("#87AB39", "Sushi");
        colorDictionary.put("#885342", "Spicy Mix");
        colorDictionary.put("#886221", "Kumera");
        colorDictionary.put("#888387", "Suva Gray");
        colorDictionary.put("#888D65", "Avocado");
        colorDictionary.put("#893456", "Camelot");
        colorDictionary.put("#893843", "Solid Pink");
        colorDictionary.put("#894367", "Cannon Pink");
        colorDictionary.put("#897D6D", "Makara");
        colorDictionary.put("#8A3324", "Burnt Umber");
        colorDictionary.put("#8A73D6", "True V");
        colorDictionary.put("#8A8360", "Clay Creek");
        colorDictionary.put("#8A8389", "Monsoon");
        colorDictionary.put("#8A8F8A", "Stack");
        colorDictionary.put("#8AB9F1", "Jordy Blue");
        colorDictionary.put("#8B00FF", "Electric Violet");
        colorDictionary.put("#8B0723", "Monarch");
        colorDictionary.put("#8B6B0B", "Corn Harvest");
        colorDictionary.put("#8B8470", "Olive Haze");
        colorDictionary.put("#8B847E", "Schooner");
        colorDictionary.put("#8B8680", "Natural Gray");
        colorDictionary.put("#8B9C90", "Mantle");
        colorDictionary.put("#8B9FEE", "Portage");
        colorDictionary.put("#8BA690", "Envy");
        colorDictionary.put("#8BA9A5", "Cascade");
        colorDictionary.put("#8BE6D8", "Riptide");
        colorDictionary.put("#8C055E", "Cardinal Pink");
        colorDictionary.put("#8C472F", "Mule Fawn");
        colorDictionary.put("#8C5738", "Potters Clay");
        colorDictionary.put("#8C6495", "Trendy Pink");
        colorDictionary.put("#8D0226", "Paprika");
        colorDictionary.put("#8D3D38", "Sanguine Brown");
        colorDictionary.put("#8D3F3F", "Tosca");
        colorDictionary.put("#8D7662", "Cement");
        colorDictionary.put("#8D8974", "Granite Green");
        colorDictionary.put("#8D90A1", "Manatee");
        colorDictionary.put("#8DA8CC", "Polo Blue");
        colorDictionary.put("#8E0000", "Red Berry");
        colorDictionary.put("#8E4D1E", "Rope");
        colorDictionary.put("#8E6F70", "Opium");
        colorDictionary.put("#8E775E", "Domino");
        colorDictionary.put("#8E8190", "Mamba");
        colorDictionary.put("#8EABC1", "Nepal");
        colorDictionary.put("#8F021C", "Pohutukawa");
        colorDictionary.put("#8F3E33", "El Salva");
        colorDictionary.put("#8F4B0E", "Korma");
        colorDictionary.put("#8F8176", "Squirrel");
        colorDictionary.put("#8FD6B4", "Vista Blue");
        colorDictionary.put("#900020", "Burgundy");
        colorDictionary.put("#901E1E", "Old Brick");
        colorDictionary.put("#907874", "Hemp");
        colorDictionary.put("#907B71", "Almond Frost");
        colorDictionary.put("#908D39", "Sycamore");
        colorDictionary.put("#92000A", "Sangria");
        colorDictionary.put("#924321", "Cumin");
        colorDictionary.put("#926F5B", "Beaver");
        colorDictionary.put("#928573", "Stonewall");
        colorDictionary.put("#928590", "Venus");
        colorDictionary.put("#9370DB", "Medium Purple");
        colorDictionary.put("#93CCEA", "Cornflower");
        colorDictionary.put("#93DFB8", "Algae Green");
        colorDictionary.put("#944747", "Copper Rust");
        colorDictionary.put("#948771", "Arrowtown");
        colorDictionary.put("#950015", "Scarlett");
        colorDictionary.put("#956387", "Strikemaster");
        colorDictionary.put("#959396", "Mountain Mist");
        colorDictionary.put("#960018", "Carmine");
        colorDictionary.put("#964B00", "Brown");
        colorDictionary.put("#967059", "Leather");
        colorDictionary.put("#9678B6", "Purple Mountain's Majesty");
        colorDictionary.put("#967BB6", "Lavender Purple");
        colorDictionary.put("#96A8A1", "Pewter");
        colorDictionary.put("#96BBAB", "Summer Green");
        colorDictionary.put("#97605D", "Au Chico");
        colorDictionary.put("#9771B5", "Wisteria");
        colorDictionary.put("#97CD2D", "Atlantis");
        colorDictionary.put("#983D61", "Vin Rouge");
        colorDictionary.put("#9874D3", "Lilac Bush");
        colorDictionary.put("#98777B", "Bazaar");
        colorDictionary.put("#98811B", "Hacienda");
        colorDictionary.put("#988D77", "Pale Oyster");
        colorDictionary.put("#98FF98", "Mint Green");
        colorDictionary.put("#990066", "Fresh Eggplant");
        colorDictionary.put("#991199", "Violet Eggplant");
        colorDictionary.put("#991613", "Tamarillo");
        colorDictionary.put("#991B07", "Totem Pole");
        colorDictionary.put("#996666", "Copper Rose");
        colorDictionary.put("#9966CC", "Amethyst");
        colorDictionary.put("#997A8D", "Mountbatten Pink");
        colorDictionary.put("#9999CC", "Blue Bell");
        colorDictionary.put("#9A3820", "Prairie Sand");
        colorDictionary.put("#9A6E61", "Toast");
        colorDictionary.put("#9A9577", "Gurkha");
        colorDictionary.put("#9AB973", "Olivine");
        colorDictionary.put("#9AC2B8", "Shadow Green");
        colorDictionary.put("#9B4703", "Oregon");
        colorDictionary.put("#9B9E8F", "Lemon Grass");
        colorDictionary.put("#9C3336", "Stiletto");
        colorDictionary.put("#9D5616", "Hawaiian Tan");
        colorDictionary.put("#9DACB7", "Gull Gray");
        colorDictionary.put("#9DC209", "Pistachio");
        colorDictionary.put("#9DE093", "Granny Smith Apple");
        colorDictionary.put("#9DE5FF", "Anakiwa");
        colorDictionary.put("#9E5302", "Chelsea Gem");
        colorDictionary.put("#9E5B40", "Sepia Skin");
        colorDictionary.put("#9EA587", "Sage");
        colorDictionary.put("#9EA91F", "Citron");
        colorDictionary.put("#9EB1CD", "Rock Blue");
        colorDictionary.put("#9EDEE0", "Morning Glory");
        colorDictionary.put("#9F381D", "Cognac");
        colorDictionary.put("#9F821C", "Reef Gold");
        colorDictionary.put("#9F9F9C", "Star Dust");
        colorDictionary.put("#9FA0B1", "Santas Gray");
        colorDictionary.put("#9FD7D3", "Sinbad");
        colorDictionary.put("#9FDD8C", "Feijoa");
        colorDictionary.put("#A02712", "Tabasco");
        colorDictionary.put("#A1750D", "Buttered Rum");
        colorDictionary.put("#A1ADB5", "Hit Gray");
        colorDictionary.put("#A1C50A", "Citrus");
        colorDictionary.put("#A1DAD7", "Aqua Island");
        colorDictionary.put("#A1E9DE", "Water Leaf");
        colorDictionary.put("#A2006D", "Flirt");
        colorDictionary.put("#A23B6C", "Rouge");
        colorDictionary.put("#A26645", "Cape Palliser");
        colorDictionary.put("#A2AAB3", "Gray Chateau");
        colorDictionary.put("#A2AEAB", "Edward");
        colorDictionary.put("#A3807B", "Pharlap");
        colorDictionary.put("#A397B4", "Amethyst Smoke");
        colorDictionary.put("#A3E3ED", "Blizzard Blue");
        colorDictionary.put("#A4A49D", "Delta");
        colorDictionary.put("#A4A6D3", "Wistful");
        colorDictionary.put("#A4AF6E", "Green Smoke");
        colorDictionary.put("#A50B5E", "Jazzberry Jam");
        colorDictionary.put("#A59B91", "Zorba");
        colorDictionary.put("#A5CB0C", "Bahia");
        colorDictionary.put("#A62F20", "Roof Terracotta");
        colorDictionary.put("#A65529", "Paarl");
        colorDictionary.put("#A68B5B", "Barley Corn");
        colorDictionary.put("#A69279", "Donkey Brown");
        colorDictionary.put("#A6A29A", "Dawn");
        colorDictionary.put("#A72525", "Mexican Red");
        colorDictionary.put("#A7882C", "Luxor Gold");
        colorDictionary.put("#A85307", "Rich Gold");
        colorDictionary.put("#A86515", "Reno Sand");
        colorDictionary.put("#A86B6B", "Coral Tree");
        colorDictionary.put("#A8989B", "Dusty Gray");
        colorDictionary.put("#A899E6", "Dull Lavender");
        colorDictionary.put("#A8A589", "Tallow");
        colorDictionary.put("#A8AE9C", "Bud");
        colorDictionary.put("#A8AF8E", "Locust");
        colorDictionary.put("#A8BD9F", "Norway");
        colorDictionary.put("#A8E3BD", "Chinook");
        colorDictionary.put("#A9A491", "Gray Olive");
        colorDictionary.put("#A9ACB6", "Aluminium");
        colorDictionary.put("#A9B2C3", "Cadet Blue");
        colorDictionary.put("#A9B497", "Schist");
        colorDictionary.put("#A9BDBF", "Tower Gray");
        colorDictionary.put("#A9BEF2", "Perano");
        colorDictionary.put("#A9C6C2", "Opal");
        colorDictionary.put("#AA375A", "Night Shadz");
        colorDictionary.put("#AA4203", "Fire");
        colorDictionary.put("#AA8B5B", "Muesli");
        colorDictionary.put("#AA8D6F", "Sandal");
        colorDictionary.put("#AAA5A9", "Shady Lady");
        colorDictionary.put("#AAA9CD", "Logan");
        colorDictionary.put("#AAABB7", "Spun Pearl");
        colorDictionary.put("#AAD6E6", "Regent St Blue");
        colorDictionary.put("#AAF0D1", "Magic Mint");
        colorDictionary.put("#AB0563", "Lipstick");
        colorDictionary.put("#AB3472", "Royal Heath");
        colorDictionary.put("#AB917A", "Sandrift");
        colorDictionary.put("#ABA0D9", "Cold Purple");
        colorDictionary.put("#ABA196", "Bronco");
        colorDictionary.put("#AC8A56", "Limed Oak");
        colorDictionary.put("#AC91CE", "East Side");
        colorDictionary.put("#AC9E22", "Lemon Ginger");
        colorDictionary.put("#ACA494", "Napa");
        colorDictionary.put("#ACA586", "Hillary");
        colorDictionary.put("#ACA59F", "Cloudy");
        colorDictionary.put("#ACACAC", "Silver Chalice");
        colorDictionary.put("#ACB78E", "Swamp Green");
        colorDictionary.put("#ACCBB1", "Spring Rain");
        colorDictionary.put("#ACDD4D", "Conifer");
        colorDictionary.put("#ACE1AF", "Celadon");
        colorDictionary.put("#AD781B", "Mandalay");
        colorDictionary.put("#ADBED1", "Casper");
        colorDictionary.put("#ADDFAD", "Moss Green");
        colorDictionary.put("#ADE6C4", "Padua");
        colorDictionary.put("#ADFF2F", "Green Yellow");
        colorDictionary.put("#AE4560", "Hippie Pink");
        colorDictionary.put("#AE6020", "Desert");
        colorDictionary.put("#AE809E", "Bouquet");
        colorDictionary.put("#AF4035", "Medium Carmine");
        colorDictionary.put("#AF4D43", "Apple Blossom");
        colorDictionary.put("#AF593E", "Brown Rust");
        colorDictionary.put("#AF8751", "Driftwood");
        colorDictionary.put("#AF8F2C", "Alpine");
        colorDictionary.put("#AF9F1C", "Lucky");
        colorDictionary.put("#AFA09E", "Martini");
        colorDictionary.put("#AFB1B8", "Bombay");
        colorDictionary.put("#AFBDD9", "Pigeon Post");
        colorDictionary.put("#B04C6A", "Cadillac");
        colorDictionary.put("#B05D54", "Matrix");
        colorDictionary.put("#B05E81", "Tapestry");
        colorDictionary.put("#B06608", "Mai Tai");
        colorDictionary.put("#B09A95", "Del Rio");
        colorDictionary.put("#B0E0E6", "Powder Blue");
        colorDictionary.put("#B0E313", "Inch Worm");
        colorDictionary.put("#B10000", "Bright Red");
        colorDictionary.put("#B14A0B", "Vesuvius");
        colorDictionary.put("#B1610B", "Pumpkin Skin");
        colorDictionary.put("#B16D52", "Santa Fe");
        colorDictionary.put("#B19461", "Teak");
        colorDictionary.put("#B1E2C1", "Fringy Flower");
        colorDictionary.put("#B1F4E7", "Ice Cold");
        colorDictionary.put("#B20931", "Shiraz");
        colorDictionary.put("#B2A1EA", "Biloba Flower");
        colorDictionary.put("#B32D29", "Tall Poppy");
        colorDictionary.put("#B35213", "Fiery Orange");
        colorDictionary.put("#B38007", "Hot Toddy");
        colorDictionary.put("#B3AF95", "Taupe Gray");
        colorDictionary.put("#B3C110", "La Rioja");
        colorDictionary.put("#B43332", "Well Read");
        colorDictionary.put("#B44668", "Blush");
        colorDictionary.put("#B4CFD3", "Jungle Mist");
        colorDictionary.put("#B57281", "Turkish Rose");
        colorDictionary.put("#B57EDC", "Lavender");
        colorDictionary.put("#B5A27F", "Mongoose");
        colorDictionary.put("#B5B35C", "Olive Green");
        colorDictionary.put("#B5D2CE", "Jet Stream");
        colorDictionary.put("#B5ECDF", "Cruise");
        colorDictionary.put("#B6316C", "Hibiscus");
        colorDictionary.put("#B69D98", "Thatch");
        colorDictionary.put("#B6B095", "Heathered Gray");
        colorDictionary.put("#B6BAA4", "Eagle");
        colorDictionary.put("#B6D1EA", "Spindle");
        colorDictionary.put("#B6D3BF", "Gum Leaf");
        colorDictionary.put("#B7410E", "Rust");
        colorDictionary.put("#B78E5C", "Muddy Waters");
        colorDictionary.put("#B7A214", "Sahara");
        colorDictionary.put("#B7A458", "Husk");
        colorDictionary.put("#B7B1B1", "Nobel");
        colorDictionary.put("#B7C3D0", "Heather");
        colorDictionary.put("#B7F0BE", "Madang");
        colorDictionary.put("#B81104", "Milano Red");
        colorDictionary.put("#B87333", "Copper");
        colorDictionary.put("#B8B56A", "Gimblet");
        colorDictionary.put("#B8C1B1", "Green Spring");
        colorDictionary.put("#B8C25D", "Celery");
        colorDictionary.put("#B8E0F9", "Sail");
        colorDictionary.put("#B94E48", "Chestnut");
        colorDictionary.put("#B95140", "Crail");
        colorDictionary.put("#B98D28", "Marigold");
        colorDictionary.put("#B9C46A", "Wild Willow");
        colorDictionary.put("#B9C8AC", "Rainee");
        colorDictionary.put("#BA0101", "Guardsman Red");
        colorDictionary.put("#BA450C", "Rock Spray");
        colorDictionary.put("#BA6F1E", "Bourbon");
        colorDictionary.put("#BA7F03", "Pirate Gold");
        colorDictionary.put("#BAB1A2", "Nomad");
        colorDictionary.put("#BAC7C9", "Submarine");
        colorDictionary.put("#BAEEF9", "Charlotte");
        colorDictionary.put("#BB3385", "Medium Red Violet");
        colorDictionary.put("#BB8983", "Brandy Rose");
        colorDictionary.put("#BBD009", "Rio Grande");
        colorDictionary.put("#BBD7C1", "Surf");
        colorDictionary.put("#BCC9C2", "Powder Ash");
        colorDictionary.put("#BD5E2E", "Tuscany");
        colorDictionary.put("#BD978E", "Quicksand");
        colorDictionary.put("#BDB1A8", "Silk");
        colorDictionary.put("#BDB2A1", "Malta");
        colorDictionary.put("#BDB3C7", "Chatelle");
        colorDictionary.put("#BDBBD7", "Lavender Gray");
        colorDictionary.put("#BDBDC6", "French Gray");
        colorDictionary.put("#BDC8B3", "Clay Ash");
        colorDictionary.put("#BDC9CE", "Loblolly");
        colorDictionary.put("#BDEDFD", "French Pass");
        colorDictionary.put("#BEA6C3", "London Hue");
        colorDictionary.put("#BEB5B7", "Pink Swan");
        colorDictionary.put("#BEDE0D", "Fuego");
        colorDictionary.put("#BF5500", "Rose of Sharon");
        colorDictionary.put("#BFB8B0", "Tide");
        colorDictionary.put("#BFBED8", "Blue Haze");
        colorDictionary.put("#BFC1C2", "Silver Sand");
        colorDictionary.put("#BFC921", "Key Lime Pie");
        colorDictionary.put("#BFDBE2", "Ziggurat");
        colorDictionary.put("#BFFF00", "Lime");
        colorDictionary.put("#C02B18", "Thunderbird");
        colorDictionary.put("#C04737", "Mojo");
        colorDictionary.put("#C08081", "Old Rose");
        colorDictionary.put("#C0C0C0", "Silver");
        colorDictionary.put("#C0D3B9", "Pale Leaf");
        colorDictionary.put("#C0D8B6", "Pixie Green");
        colorDictionary.put("#C1440E", "Tia Maria");
        colorDictionary.put("#C154C1", "Fuchsia Pink");
        colorDictionary.put("#C1A004", "Buddha Gold");
        colorDictionary.put("#C1B7A4", "Bison Hide");
        colorDictionary.put("#C1BAB0", "Tea");
        colorDictionary.put("#C1BECD", "Gray Suit");
        colorDictionary.put("#C1D7B0", "Sprout");
        colorDictionary.put("#C1F07C", "Sulu");
        colorDictionary.put("#C26B03", "Indochine");
        colorDictionary.put("#C2955D", "Twine");
        colorDictionary.put("#C2BDB6", "Cotton Seed");
        colorDictionary.put("#C2CAC4", "Pumice");
        colorDictionary.put("#C2E8E5", "Jagged Ice");
        colorDictionary.put("#C32148", "Maroon Flush");
        colorDictionary.put("#C3B091", "Indian Khaki");
        colorDictionary.put("#C3BFC1", "Pale Slate");
        colorDictionary.put("#C3C3BD", "Gray Nickel");
        colorDictionary.put("#C3CDE6", "Periwinkle Gray");
        colorDictionary.put("#C3D1D1", "Tiara");
        colorDictionary.put("#C3DDF9", "Tropical Blue");
        colorDictionary.put("#C41E3A", "Cardinal");
        colorDictionary.put("#C45655", "Fuzzy Wuzzy Brown");
        colorDictionary.put("#C45719", "Orange Roughy");
        colorDictionary.put("#C4C4BC", "Mist Gray");
        colorDictionary.put("#C4D0B0", "Coriander");
        colorDictionary.put("#C4F4EB", "Mint Tulip");
        colorDictionary.put("#C54B8C", "Mulberry");
        colorDictionary.put("#C59922", "Nugget");
        colorDictionary.put("#C5994B", "Tussock");
        colorDictionary.put("#C5DBCA", "Sea Mist");
        colorDictionary.put("#C5E17A", "Yellow Green");
        colorDictionary.put("#C62D42", "Brick Red");
        colorDictionary.put("#C6726B", "Contessa");
        colorDictionary.put("#C69191", "Oriental Pink");
        colorDictionary.put("#C6A84B", "Roti");
        colorDictionary.put("#C6C3B5", "Ash");
        colorDictionary.put("#C6C8BD", "Kangaroo");
        colorDictionary.put("#C6E610", "Las Palmas");
        colorDictionary.put("#C7031E", "Monza");
        colorDictionary.put("#C71585", "Red Violet");
        colorDictionary.put("#C7BCA2", "Coral Reef");
        colorDictionary.put("#C7C1FF", "Melrose");
        colorDictionary.put("#C7C4BF", "Cloud");
        colorDictionary.put("#C7C9D5", "Ghost");
        colorDictionary.put("#C7CD90", "Pine Glade");
        colorDictionary.put("#C7DDE5", "Botticelli");
        colorDictionary.put("#C88A65", "Antique Brass");
        colorDictionary.put("#C8A2C8", "Lilac");
        colorDictionary.put("#C8A528", "Hokey Pokey");
        colorDictionary.put("#C8AABF", "Lily");
        colorDictionary.put("#C8B568", "Laser");
        colorDictionary.put("#C8E3D7", "Edgewater");
        colorDictionary.put("#C96323", "Piper");
        colorDictionary.put("#C99415", "Pizza");
        colorDictionary.put("#C9A0DC", "Light Wisteria");
        colorDictionary.put("#C9B29B", "Rodeo Dust");
        colorDictionary.put("#C9B35B", "Sundance");
        colorDictionary.put("#C9B93B", "Earls Green");
        colorDictionary.put("#C9C0BB", "Silver Rust");
        colorDictionary.put("#C9D9D2", "Conch");
        colorDictionary.put("#C9FFA2", "Reef");
        colorDictionary.put("#C9FFE5", "Aero Blue");
        colorDictionary.put("#CA3435", "Flush Mahogany");
        colorDictionary.put("#CABB48", "Turmeric");
        colorDictionary.put("#CADCD4", "Paris White");
        colorDictionary.put("#CAE00D", "Bitter Lemon");
        colorDictionary.put("#CAE6DA", "Skeptic");
        colorDictionary.put("#CB8FA9", "Viola");
        colorDictionary.put("#CBCAB6", "Foggy Gray");
        colorDictionary.put("#CBD3B0", "Green Mist");
        colorDictionary.put("#CBDBD6", "Nebula");
        colorDictionary.put("#CC3333", "Persian Red");
        colorDictionary.put("#CC5500", "Burnt Orange");
        colorDictionary.put("#CC7722", "Ochre");
        colorDictionary.put("#CC8899", "Puce");
        colorDictionary.put("#CCCAA8", "Thistle Green");
        colorDictionary.put("#CCCCFF", "Periwinkle");
        colorDictionary.put("#CCFF00", "Electric Lime");
        colorDictionary.put("#CD5700", "Tenn");
        colorDictionary.put("#CD5C5C", "Chestnut Rose");
        colorDictionary.put("#CD8429", "Brandy Punch");
        colorDictionary.put("#CDF4FF", "Onahau");
        colorDictionary.put("#CEB98F", "Sorrell Brown");
        colorDictionary.put("#CEBABA", "Cold Turkey");
        colorDictionary.put("#CEC291", "Yuma");
        colorDictionary.put("#CEC7A7", "Chino");
        colorDictionary.put("#CFA39D", "Eunry");
        colorDictionary.put("#CFB53B", "Old Gold");
        colorDictionary.put("#CFDCCF", "Tasman");
        colorDictionary.put("#CFE5D2", "Surf Crest");
        colorDictionary.put("#CFF9F3", "Humming Bird");
        colorDictionary.put("#CFFAF4", "Scandal");
        colorDictionary.put("#D05F04", "Red Stage");
        colorDictionary.put("#D06DA1", "Hopbush");
        colorDictionary.put("#D07D12", "Meteor");
        colorDictionary.put("#D0BEF8", "Perfume");
        colorDictionary.put("#D0C0E5", "Prelude");
        colorDictionary.put("#D0F0C0", "Tea Green");
        colorDictionary.put("#D18F1B", "Geebung");
        colorDictionary.put("#D1BEA8", "Vanilla");
        colorDictionary.put("#D1C6B4", "Soft Amber");
        colorDictionary.put("#D1D2CA", "Celeste");
        colorDictionary.put("#D1D2DD", "Mischka");
        colorDictionary.put("#D1E231", "Pear");
        colorDictionary.put("#D2691E", "Hot Cinnamon");
        colorDictionary.put("#D27D46", "Raw Sienna");
        colorDictionary.put("#D29EAA", "Careys Pink");
        colorDictionary.put("#D2B48C", "Tan");
        colorDictionary.put("#D2DA97", "Deco");
        colorDictionary.put("#D2F6DE", "Blue Romance");
        colorDictionary.put("#D2F8B0", "Gossip");
        colorDictionary.put("#D3CBBA", "Sisal");
        colorDictionary.put("#D3CDC5", "Swirl");
        colorDictionary.put("#D47494", "Charm");
        colorDictionary.put("#D4B6AF", "Clam Shell");
        colorDictionary.put("#D4BF8D", "Straw");
        colorDictionary.put("#D4C4A8", "Akaroa");
        colorDictionary.put("#D4CD16", "Bird Flower");
        colorDictionary.put("#D4D7D9", "Iron");
        colorDictionary.put("#D4DFE2", "Geyser");
        colorDictionary.put("#D4E2FC", "Hawkes Blue");
        colorDictionary.put("#D54600", "Grenadier");
        colorDictionary.put("#D591A4", "Can Can");
        colorDictionary.put("#D59A6F", "Whiskey");
        colorDictionary.put("#D5D195", "Winter Hazel");
        colorDictionary.put("#D5F6E3", "Granny Apple");
        colorDictionary.put("#D69188", "My Pink");
        colorDictionary.put("#D6C562", "Tacha");
        colorDictionary.put("#D6CEF6", "Moon Raker");
        colorDictionary.put("#D6D6D1", "Quill Gray");
        colorDictionary.put("#D6FFDB", "Snowy Mint");
        colorDictionary.put("#D7837F", "New York Pink");
        colorDictionary.put("#D7C498", "Pavlova");
        colorDictionary.put("#D7D0FF", "Fog");
        colorDictionary.put("#D84437", "Valencia");
        colorDictionary.put("#D87C63", "Japonica");
        colorDictionary.put("#D8BFD8", "Thistle");
        colorDictionary.put("#D8C2D5", "Maverick");
        colorDictionary.put("#D8FCFA", "Foam");
        colorDictionary.put("#D94972", "Cabaret");
        colorDictionary.put("#D99376", "Burning Sand");
        colorDictionary.put("#D9B99B", "Cameo");
        colorDictionary.put("#D9D6CF", "Timberwolf");
        colorDictionary.put("#D9DCC1", "Tana");
        colorDictionary.put("#D9E4F5", "Link Water");
        colorDictionary.put("#D9F7FF", "Mabel");
        colorDictionary.put("#DA3287", "Cerise");
        colorDictionary.put("#DA5B38", "Flame Pea");
        colorDictionary.put("#DA6304", "Bamboo");
        colorDictionary.put("#DA6A41", "Red Damask");
        colorDictionary.put("#DA70D6", "Orchid");
        colorDictionary.put("#DA8A67", "Copperfield");
        colorDictionary.put("#DAA520", "Golden Grass");
        colorDictionary.put("#DAECD6", "Zanah");
        colorDictionary.put("#DAF4F0", "Iceberg");
        colorDictionary.put("#DAFAFF", "Oyster Bay");
        colorDictionary.put("#DB5079", "Cranberry");
        colorDictionary.put("#DB9690", "Petite Orchid");
        colorDictionary.put("#DB995E", "Di Serria");
        colorDictionary.put("#DBDBDB", "Alto");
        colorDictionary.put("#DBFFF8", "Frosted Mint");
        colorDictionary.put("#DC143C", "Crimson");
        colorDictionary.put("#DC4333", "Punch");
        colorDictionary.put("#DCB20C", "Galliano");
        colorDictionary.put("#DCB4BC", "Blossom");
        colorDictionary.put("#DCD747", "Wattle");
        colorDictionary.put("#DCD9D2", "Westar");
        colorDictionary.put("#DCDDCC", "Moon Mist");
        colorDictionary.put("#DCEDB4", "Caper");
        colorDictionary.put("#DCF0EA", "Swans Down");
        colorDictionary.put("#DDD6D5", "Swiss Coffee");
        colorDictionary.put("#DDF9F1", "White Ice");
        colorDictionary.put("#DE3163", "Cerise Red");
        colorDictionary.put("#DE6360", "Roman");
        colorDictionary.put("#DEA681", "Tumbleweed");
        colorDictionary.put("#DEBA13", "Gold Tips");
        colorDictionary.put("#DEC196", "Brandy");
        colorDictionary.put("#DECBC6", "Wafer");
        colorDictionary.put("#DED4A4", "Sapling");
        colorDictionary.put("#DED717", "Barberry");
        colorDictionary.put("#DEE5C0", "Beryl Green");
        colorDictionary.put("#DEF5FF", "Pattens Blue");
        colorDictionary.put("#DF73FF", "Heliotrope");
        colorDictionary.put("#DFBE6F", "Apache");
        colorDictionary.put("#DFCD6F", "Chenin");
        colorDictionary.put("#DFCFDB", "Lola");
        colorDictionary.put("#DFECDA", "Willow Brook");
        colorDictionary.put("#DFFF00", "Chartreuse Yellow");
        colorDictionary.put("#E0B0FF", "Mauve");
        colorDictionary.put("#E0B646", "Anzac");
        colorDictionary.put("#E0B974", "Harvest Gold");
        colorDictionary.put("#E0C095", "Calico");
        colorDictionary.put("#E0FFFF", "Baby Blue");
        colorDictionary.put("#E16865", "Sunglo");
        colorDictionary.put("#E1BC64", "Equator");
        colorDictionary.put("#E1C0C8", "Pink Flare");
        colorDictionary.put("#E1E6D6", "Periglacial Blue");
        colorDictionary.put("#E1EAD4", "Kidnapper");
        colorDictionary.put("#E1F6E8", "Tara");
        colorDictionary.put("#E25465", "Mandy");
        colorDictionary.put("#E2725B", "Terracotta");
        colorDictionary.put("#E28913", "Golden Bell");
        colorDictionary.put("#E292C0", "Shocking");
        colorDictionary.put("#E29418", "Dixie");
        colorDictionary.put("#E29CD2", "Light Orchid");
        colorDictionary.put("#E2D8ED", "Snuff");
        colorDictionary.put("#E2EBED", "Mystic");
        colorDictionary.put("#E2F3EC", "Apple Green");
        colorDictionary.put("#E30B5C", "Razzmatazz");
        colorDictionary.put("#E32636", "Alizarin Crimson");
        colorDictionary.put("#E34234", "Cinnabar");
        colorDictionary.put("#E3BEBE", "Cavern Pink");
        colorDictionary.put("#E3F5E1", "Peppermint");
        colorDictionary.put("#E3F988", "Mindaro");
        colorDictionary.put("#E47698", "Deep Blush");
        colorDictionary.put("#E49B0F", "Gamboge");
        colorDictionary.put("#E4C2D5", "Melanie");
        colorDictionary.put("#E4CFDE", "Twilight");
        colorDictionary.put("#E4D1C0", "Bone");
        colorDictionary.put("#E4D422", "Sunflower");
        colorDictionary.put("#E4D5B7", "Grain Brown");
        colorDictionary.put("#E4D69B", "Zombie");
        colorDictionary.put("#E4F6E7", "Frostee");
        colorDictionary.put("#E4FFD1", "Snow Flurry");
        colorDictionary.put("#E52B50", "Amaranth");
        colorDictionary.put("#E5841B", "Zest");
        colorDictionary.put("#E5CCC9", "Dust Storm");
        colorDictionary.put("#E5D7BD", "Stark White");
        colorDictionary.put("#E5D8AF", "Hampton");
        colorDictionary.put("#E5E0E1", "Bon Jour");
        colorDictionary.put("#E5E5E5", "Mercury");
        colorDictionary.put("#E5F9F6", "Polar");
        colorDictionary.put("#E64E03", "Trinidad");
        colorDictionary.put("#E6BE8A", "Gold Sand");
        colorDictionary.put("#E6BEA5", "Cashmere");
        colorDictionary.put("#E6D7B9", "Double Spanish White");
        colorDictionary.put("#E6E4D4", "Satin Linen");
        colorDictionary.put("#E6F2EA", "Harp");
        colorDictionary.put("#E6F8F3", "Off Green");
        colorDictionary.put("#E6FFE9", "Hint of Green");
        colorDictionary.put("#E6FFFF", "Tranquil");
        colorDictionary.put("#E77200", "Mango Tango");
        colorDictionary.put("#E7730A", "Christine");
        colorDictionary.put("#E79F8C", "Tonys Pink");
        colorDictionary.put("#E79FC4", "Kobi");
        colorDictionary.put("#E7BCB4", "Rose Fog");
        colorDictionary.put("#E7BF05", "Corn");
        colorDictionary.put("#E7CD8C", "Putty");
        colorDictionary.put("#E7ECE6", "Gray Nurse");
        colorDictionary.put("#E7F8FF", "Lily White");
        colorDictionary.put("#E7FEFF", "Bubbles");
        colorDictionary.put("#E89928", "Fire Bush");
        colorDictionary.put("#E8B9B3", "Shilo");
        colorDictionary.put("#E8E0D5", "Pearl Bush");
        colorDictionary.put("#E8EBE0", "Green White");
        colorDictionary.put("#E8F1D4", "Chrome White");
        colorDictionary.put("#E8F2EB", "Gin");
        colorDictionary.put("#E8F5F2", "Aqua Squeeze");
        colorDictionary.put("#E96E00", "Clementine");
        colorDictionary.put("#E97451", "Burnt Sienna");
        colorDictionary.put("#E97C07", "Tahiti Gold");
        colorDictionary.put("#E9CECD", "Oyster Pink");
        colorDictionary.put("#E9D75A", "Confetti");
        colorDictionary.put("#E9E3E3", "Ebb");
        colorDictionary.put("#E9F8ED", "Ottoman");
        colorDictionary.put("#E9FFFD", "Clear Day");
        colorDictionary.put("#EA88A8", "Carissma");
        colorDictionary.put("#EAAE69", "Porsche");
        colorDictionary.put("#EAB33B", "Tulip Tree");
        colorDictionary.put("#EAC674", "Rob Roy");
        colorDictionary.put("#EADAB8", "Raffia");
        colorDictionary.put("#EAE8D4", "White Rock");
        colorDictionary.put("#EAF6EE", "Panache");
        colorDictionary.put("#EAF6FF", "Solitude");
        colorDictionary.put("#EAF9F5", "Aqua Spring");
        colorDictionary.put("#EAFFFE", "Dew");
        colorDictionary.put("#EB9373", "Apricot");
        colorDictionary.put("#EBC2AF", "Zinnwaldite");
        colorDictionary.put("#ECA927", "Fuel Yellow");
        colorDictionary.put("#ECC54E", "Ronchi");
        colorDictionary.put("#ECC7EE", "French Lilac");
        colorDictionary.put("#ECCDB9", "Just Right");
        colorDictionary.put("#ECE090", "Wild Rice");
        colorDictionary.put("#ECEBBD", "Fall Green");
        colorDictionary.put("#ECEBCE", "Aths Special");
        colorDictionary.put("#ECF245", "Starship");
        colorDictionary.put("#ED0A3F", "Red Ribbon");
        colorDictionary.put("#ED7A1C", "Tango");
        colorDictionary.put("#ED9121", "Carrot Orange");
        colorDictionary.put("#ED989E", "Sea Pink");
        colorDictionary.put("#EDB381", "Tacao");
        colorDictionary.put("#EDC9AF", "Desert Sand");
        colorDictionary.put("#EDCDAB", "Pancho");
        colorDictionary.put("#EDDCB1", "Chamois");
        colorDictionary.put("#EDEA99", "Primrose");
        colorDictionary.put("#EDF5DD", "Frost");
        colorDictionary.put("#EDF5F5", "Aqua Haze");
        colorDictionary.put("#EDF6FF", "Zumthor");
        colorDictionary.put("#EDF9F1", "Narvik");
        colorDictionary.put("#EDFC84", "Honeysuckle");
        colorDictionary.put("#EE82EE", "Lavender Magenta");
        colorDictionary.put("#EEC1BE", "Beauty Bush");
        colorDictionary.put("#EED794", "Chalky");
        colorDictionary.put("#EED9C4", "Almond");
        colorDictionary.put("#EEDC82", "Flax");
        colorDictionary.put("#EEDEDA", "Bizarre");
        colorDictionary.put("#EEE3AD", "Double Colonial White");
        colorDictionary.put("#EEEEE8", "Cararra");
        colorDictionary.put("#EEEF78", "Manz");
        colorDictionary.put("#EEF0C8", "Tahuna Sands");
        colorDictionary.put("#EEF0F3", "Athens Gray");
        colorDictionary.put("#EEF3C3", "Tusk");
        colorDictionary.put("#EEF4DE", "Loafer");
        colorDictionary.put("#EEF6F7", "Catskill White");
        colorDictionary.put("#EEFDFF", "Twilight Blue");
        colorDictionary.put("#EEFF9A", "Jonquil");
        colorDictionary.put("#EEFFE2", "Rice Flower");
        colorDictionary.put("#EF863F", "Jaffa");
        colorDictionary.put("#EFEFEF", "Gallery");
        colorDictionary.put("#EFF2F3", "Porcelain");
        colorDictionary.put("#F091A9", "Mauvelous");
        colorDictionary.put("#F0D52D", "Golden Dream");
        colorDictionary.put("#F0DB7D", "Golden Sand");
        colorDictionary.put("#F0DC82", "Buff");
        colorDictionary.put("#F0E2EC", "Prim");
        colorDictionary.put("#F0E68C", "Khaki");
        colorDictionary.put("#F0EEFD", "Selago");
        colorDictionary.put("#F0EEFF", "Titan White");
        colorDictionary.put("#F0F8FF", "Alice Blue");
        colorDictionary.put("#F0FCEA", "Feta");
        colorDictionary.put("#F18200", "Gold Drop");
        colorDictionary.put("#F19BAB", "Wewak");
        colorDictionary.put("#F1E788", "Sahara Sand");
        colorDictionary.put("#F1E9D2", "Parchment");
        colorDictionary.put("#F1E9FF", "Blue Chalk");
        colorDictionary.put("#F1EEC1", "Mint Julep");
        colorDictionary.put("#F1F1F1", "Seashell");
        colorDictionary.put("#F1F7F2", "Saltpan");
        colorDictionary.put("#F1FFAD", "Tidal");
        colorDictionary.put("#F1FFC8", "Chiffon");
        colorDictionary.put("#F2552A", "Flamingo");
        colorDictionary.put("#F28500", "Tangerine");
        colorDictionary.put("#F2C3B2", "Mandys Pink");
        colorDictionary.put("#F2F2F2", "Concrete");
        colorDictionary.put("#F2FAFA", "Black Squeeze");
        colorDictionary.put("#F34723", "Pomegranate");
        colorDictionary.put("#F3AD16", "Buttercup");
        colorDictionary.put("#F3D69D", "New Orleans");
        colorDictionary.put("#F3D9DF", "Vanilla Ice");
        colorDictionary.put("#F3E7BB", "Sidecar");
        colorDictionary.put("#F3E9E5", "Dawn Pink");
        colorDictionary.put("#F3EDCF", "Wheatfield");
        colorDictionary.put("#F3FB62", "Canary");
        colorDictionary.put("#F3FBD4", "Orinoco");
        colorDictionary.put("#F3FFD8", "Carla");
        colorDictionary.put("#F400A1", "Hollywood Cerise");
        colorDictionary.put("#F4A460", "Sandy brown");
        colorDictionary.put("#F4C430", "Saffron");
        colorDictionary.put("#F4D81C", "Ripe Lemon");
        colorDictionary.put("#F4EBD3", "Janna");
        colorDictionary.put("#F4F2EE", "Pampas");
        colorDictionary.put("#F4F4F4", "Wild Sand");
        colorDictionary.put("#F4F8FF", "Zircon");
        colorDictionary.put("#F57584", "Froly");
        colorDictionary.put("#F5C85C", "Cream Can");
        colorDictionary.put("#F5C999", "Manhattan");
        colorDictionary.put("#F5D5A0", "Maize");
        colorDictionary.put("#F5DEB3", "Wheat");
        colorDictionary.put("#F5E7A2", "Sandwisp");
        colorDictionary.put("#F5E7E2", "Pot Pourri");
        colorDictionary.put("#F5E9D3", "Albescent White");
        colorDictionary.put("#F5EDEF", "Soft Peach");
        colorDictionary.put("#F5F3E5", "Ecru White");
        colorDictionary.put("#F5F5DC", "Beige");
        colorDictionary.put("#F5FB3D", "Golden Fizz");
        colorDictionary.put("#F5FFBE", "Australian Mint");
        colorDictionary.put("#F64A8A", "French Rose");
        colorDictionary.put("#F653A6", "Brilliant Rose");
        colorDictionary.put("#F6A4C9", "Illusion");
        colorDictionary.put("#F6F0E6", "Merino");
        colorDictionary.put("#F6F7F7", "Black Haze");
        colorDictionary.put("#F6FFDC", "Spring Sun");
        colorDictionary.put("#F7468A", "Violet Red");
        colorDictionary.put("#F77703", "Chilean Fire");
        colorDictionary.put("#F77FBE", "Persian Pink");
        colorDictionary.put("#F7B668", "Rajah");
        colorDictionary.put("#F7C8DA", "Azalea");
        colorDictionary.put("#F7DBE6", "We Peep");
        colorDictionary.put("#F7F2E1", "Quarter Spanish White");
        colorDictionary.put("#F7F5FA", "Whisper");
        colorDictionary.put("#F7FAF7", "Snow Drift");
        colorDictionary.put("#F8B853", "Casablanca");
        colorDictionary.put("#F8C3DF", "Chantilly");
        colorDictionary.put("#F8D9E9", "Cherub");
        colorDictionary.put("#F8DB9D", "Marzipan");
        colorDictionary.put("#F8DD5C", "Energy Yellow");
        colorDictionary.put("#F8E4BF", "Givry");
        colorDictionary.put("#F8F0E8", "White Linen");
        colorDictionary.put("#F8F4FF", "Magnolia");
        colorDictionary.put("#F8F6F1", "Spring Wood");
        colorDictionary.put("#F8F7DC", "Coconut Cream");
        colorDictionary.put("#F8F7FC", "White Lilac");
        colorDictionary.put("#F8F8F7", "Desert Storm");
        colorDictionary.put("#F8F99C", "Texas");
        colorDictionary.put("#F8FACD", "Corn Field");
        colorDictionary.put("#F8FDD3", "Mimosa");
        colorDictionary.put("#F95A61", "Carnation");
        colorDictionary.put("#F9BF58", "Saffron Mango");
        colorDictionary.put("#F9E0ED", "Carousel Pink");
        colorDictionary.put("#F9E4BC", "Dairy Cream");
        colorDictionary.put("#F9E663", "Portica");
        colorDictionary.put("#F9EAF3", "Amour");
        colorDictionary.put("#F9F8E4", "Rum Swizzle");
        colorDictionary.put("#F9FF8B", "Dolly");
        colorDictionary.put("#F9FFF6", "Sugar Cane");
        colorDictionary.put("#FA7814", "Ecstasy");
        colorDictionary.put("#FA9D5A", "Tan Hide");
        colorDictionary.put("#FAD3A2", "Corvette");
        colorDictionary.put("#FADFAD", "Peach Yellow");
        colorDictionary.put("#FAE600", "Turbo");
        colorDictionary.put("#FAEAB9", "Astra");
        colorDictionary.put("#FAECCC", "Champagne");
        colorDictionary.put("#FAF0E6", "Linen");
        colorDictionary.put("#FAF3F0", "Fantasy");
        colorDictionary.put("#FAF7D6", "Citrine White");
        colorDictionary.put("#FAFAFA", "Alabaster");
        colorDictionary.put("#FAFDE4", "Hint of Yellow");
        colorDictionary.put("#FAFFA4", "Milan");
        colorDictionary.put("#FB607F", "Brink Pink");
        colorDictionary.put("#FB8989", "Geraldine");
        colorDictionary.put("#FBA0E3", "Lavender Rose");
        colorDictionary.put("#FBA129", "Sea Buckthorn");
        colorDictionary.put("#FBAC13", "Sun");
        colorDictionary.put("#FBAED2", "Lavender Pink");
        colorDictionary.put("#FBB2A3", "Rose Bud");
        colorDictionary.put("#FBBEDA", "Cupid");
        colorDictionary.put("#FBCCE7", "Classic Rose");
        colorDictionary.put("#FBCEB1", "Apricot Peach");
        colorDictionary.put("#FBE7B2", "Banana Mania");
        colorDictionary.put("#FBE870", "Marigold Yellow");
        colorDictionary.put("#FBE96C", "Festival");
        colorDictionary.put("#FBEA8C", "Sweet Corn");
        colorDictionary.put("#FBEC5D", "Candy Corn");
        colorDictionary.put("#FBF9F9", "Hint of Red");
        colorDictionary.put("#FBFFBA", "Shalimar");
        colorDictionary.put("#FC0FC0", "Shocking Pink");
        colorDictionary.put("#FC80A5", "Tickle Me Pink");
        colorDictionary.put("#FC9C1D", "Tree Poppy");
        colorDictionary.put("#FCC01E", "Lightning Yellow");
        colorDictionary.put("#FCD667", "Goldenrod");
        colorDictionary.put("#FCD917", "Candlelight");
        colorDictionary.put("#FCDA98", "Cherokee");
        colorDictionary.put("#FCF4D0", "Double Pearl Lusta");
        colorDictionary.put("#FCF4DC", "Pearl Lusta");
        colorDictionary.put("#FCF8F7", "Vista White");
        colorDictionary.put("#FCFBF3", "Bianca");
        colorDictionary.put("#FCFEDA", "Moon Glow");
        colorDictionary.put("#FCFFE7", "China Ivory");
        colorDictionary.put("#FCFFF9", "Ceramic");
        colorDictionary.put("#FD0E35", "Torch Red");
        colorDictionary.put("#FD5B78", "Wild Watermelon");
        colorDictionary.put("#FD7B33", "Crusta");
        colorDictionary.put("#FD7C07", "Sorbus");
        colorDictionary.put("#FD9FA2", "Sweet Pink");
        colorDictionary.put("#FDD5B1", "Light Apricot");
        colorDictionary.put("#FDD7E4", "Pig Pink");
        colorDictionary.put("#FDE1DC", "Cinderella");
        colorDictionary.put("#FDE295", "Golden Glow");
        colorDictionary.put("#FDE910", "Lemon");
        colorDictionary.put("#FDF5E6", "Old Lace");
        colorDictionary.put("#FDF6D3", "Half Colonial White");
        colorDictionary.put("#FDF7AD", "Drover");
        colorDictionary.put("#FDFEB8", "Pale Prim");
        colorDictionary.put("#FDFFD5", "Cumulus");
        colorDictionary.put("#FE28A2", "Persian Rose");
        colorDictionary.put("#FE4C40", "Sunset Orange");
        colorDictionary.put("#FE6F5E", "Bittersweet");
        colorDictionary.put("#FE9D04", "California");
        colorDictionary.put("#FEA904", "Yellow Sea");
        colorDictionary.put("#FEBAAD", "Melon");
        colorDictionary.put("#FED33C", "Bright Sun");
        colorDictionary.put("#FED85D", "Dandelion");
        colorDictionary.put("#FEDB8D", "Salomie");
        colorDictionary.put("#FEE5AC", "Cape Honey");
        colorDictionary.put("#FEEBF3", "Remy");
        colorDictionary.put("#FEEFCE", "Oasis");
        colorDictionary.put("#FEF0EC", "Bridesmaid");
        colorDictionary.put("#FEF2C7", "Beeswax");
        colorDictionary.put("#FEF3D8", "Bleach White");
        colorDictionary.put("#FEF4CC", "Pipi");
        colorDictionary.put("#FEF4DB", "Half Spanish White");
        colorDictionary.put("#FEF4F8", "Wisp Pink");
        colorDictionary.put("#FEF5F1", "Provincial Pink");
        colorDictionary.put("#FEF7DE", "Half Dutch White");
        colorDictionary.put("#FEF8E2", "Solitaire");
        colorDictionary.put("#FEF8FF", "White Pointer");
        colorDictionary.put("#FEF9E3", "Off Yellow");
        colorDictionary.put("#FEFCED", "Orange White");
        colorDictionary.put("#FF0000", "Red");
        colorDictionary.put("#FF007F", "Rose");
        colorDictionary.put("#FF00CC", "Purple Pizzazz");
        colorDictionary.put("#FF00FF", "Magenta / Fuchsia");
        colorDictionary.put("#FF2400", "Scarlet");
        colorDictionary.put("#FF3399", "Wild Strawberry");
        colorDictionary.put("#FF33CC", "Razzle Dazzle Rose");
        colorDictionary.put("#FF355E", "Radical Red");
        colorDictionary.put("#FF3F34", "Red Orange");
        colorDictionary.put("#FF4040", "Coral Red");
        colorDictionary.put("#FF4D00", "Vermilion");
        colorDictionary.put("#FF4F00", "International Orange");
        colorDictionary.put("#FF6037", "Outrageous Orange");
        colorDictionary.put("#FF6600", "Blaze Orange");
        colorDictionary.put("#FF66FF", "Pink Flamingo");
        colorDictionary.put("#FF681F", "Orange");
        colorDictionary.put("#FF69B4", "Hot Pink");
        colorDictionary.put("#FF6B53", "Persimmon");
        colorDictionary.put("#FF6FFF", "Blush Pink");
        colorDictionary.put("#FF7034", "Burning Orange");
        colorDictionary.put("#FF7518", "Pumpkin");
        colorDictionary.put("#FF7D07", "Flamenco");
        colorDictionary.put("#FF7F00", "Flush Orange");
        colorDictionary.put("#FF7F50", "Coral");
        colorDictionary.put("#FF8C69", "Salmon");
        colorDictionary.put("#FF9000", "Pizazz");
        colorDictionary.put("#FF910F", "West Side");
        colorDictionary.put("#FF91A4", "Pink Salmon");
        colorDictionary.put("#FF9933", "Neon Carrot");
        colorDictionary.put("#FF9966", "Atomic Tangerine");
        colorDictionary.put("#FF9980", "Vivid Tangerine");
        colorDictionary.put("#FF9E2C", "Sunshade");
        colorDictionary.put("#FFA000", "Orange Peel");
        colorDictionary.put("#FFA194", "Mona Lisa");
        colorDictionary.put("#FFA500", "Web Orange");
        colorDictionary.put("#FFA6C9", "Carnation Pink");
        colorDictionary.put("#FFAB81", "Hit Pink");
        colorDictionary.put("#FFAE42", "Yellow Orange");
        colorDictionary.put("#FFB0AC", "Cornflower Lilac");
        colorDictionary.put("#FFB1B3", "Sundown");
        colorDictionary.put("#FFB31F", "My Sin");
        colorDictionary.put("#FFB555", "Texas Rose");
        colorDictionary.put("#FFB7D5", "Cotton Candy");
        colorDictionary.put("#FFB97B", "Macaroni and Cheese");
        colorDictionary.put("#FFBA00", "Selective Yellow");
        colorDictionary.put("#FFBD5F", "Koromiko");
        colorDictionary.put("#FFBF00", "Amber");
        colorDictionary.put("#FFC0A8", "Wax Flower");
        colorDictionary.put("#FFC0CB", "Pink");
        colorDictionary.put("#FFC3C0", "Your Pink");
        colorDictionary.put("#FFC901", "Supernova");
        colorDictionary.put("#FFCBA4", "Flesh");
        colorDictionary.put("#FFCC33", "Sunglow");
        colorDictionary.put("#FFCC5C", "Golden Tainoi");
        colorDictionary.put("#FFCC99", "Peach Orange");
        colorDictionary.put("#FFCD8C", "Chardonnay");
        colorDictionary.put("#FFD1DC", "Pastel Pink");
        colorDictionary.put("#FFD2B7", "Romantic");
        colorDictionary.put("#FFD38C", "Grandis");
        colorDictionary.put("#FFD700", "Gold");
        colorDictionary.put("#FFD800", "School bus Yellow");
        colorDictionary.put("#FFD8D9", "Cosmos");
        colorDictionary.put("#FFDB58", "Mustard");
        colorDictionary.put("#FFDCD6", "Peach Schnapps");
        colorDictionary.put("#FFDDAF", "Caramel");
        colorDictionary.put("#FFDDCD", "Tuft Bush");
        colorDictionary.put("#FFDDCF", "Watusi");
        colorDictionary.put("#FFDDF4", "Pink Lace");
        colorDictionary.put("#FFDEAD", "Navajo White");
        colorDictionary.put("#FFDEB3", "Frangipani");
        colorDictionary.put("#FFE1DF", "Pippin");
        colorDictionary.put("#FFE1F2", "Pale Rose");
        colorDictionary.put("#FFE2C5", "Negroni");
        colorDictionary.put("#FFE5A0", "Cream Brulee");
        colorDictionary.put("#FFE5B4", "Peach");
        colorDictionary.put("#FFE6C7", "Tequila");
        colorDictionary.put("#FFE772", "Kournikova");
        colorDictionary.put("#FFEAC8", "Sandy Beach");
        colorDictionary.put("#FFEAD4", "Karry");
        colorDictionary.put("#FFEC13", "Broom");
        colorDictionary.put("#FFEDBC", "Colonial White");
        colorDictionary.put("#FFEED8", "Derby");
        colorDictionary.put("#FFEFA1", "Vis Vis");
        colorDictionary.put("#FFEFC1", "Egg White");
        colorDictionary.put("#FFEFD5", "Papaya Whip");
        colorDictionary.put("#FFEFEC", "Fair Pink");
        colorDictionary.put("#FFF0DB", "Peach Cream");
        colorDictionary.put("#FFF0F5", "Lavender blush");
        colorDictionary.put("#FFF14F", "Gorse");
        colorDictionary.put("#FFF1B5", "Buttermilk");
        colorDictionary.put("#FFF1D8", "Pink Lady");
        colorDictionary.put("#FFF1EE", "Forget Me Not");
        colorDictionary.put("#FFF1F9", "Tutu");
        colorDictionary.put("#FFF39D", "Picasso");
        colorDictionary.put("#FFF3F1", "Chardon");
        colorDictionary.put("#FFF46E", "Paris Daisy");
        colorDictionary.put("#FFF4CE", "Barley White");
        colorDictionary.put("#FFF4DD", "Egg Sour");
        colorDictionary.put("#FFF4E0", "Sazerac");
        colorDictionary.put("#FFF4E8", "Serenade");
        colorDictionary.put("#FFF4F3", "Chablis");
        colorDictionary.put("#FFF5EE", "Seashell Peach");
        colorDictionary.put("#FFF5F3", "Sauvignon");
        colorDictionary.put("#FFF6D4", "Milk Punch");
        colorDictionary.put("#FFF6DF", "Varden");
        colorDictionary.put("#FFF6F5", "Rose White");
        colorDictionary.put("#FFF8D1", "Baja White");
        colorDictionary.put("#FFF9E2", "Gin Fizz");
        colorDictionary.put("#FFF9E6", "Early Dawn");
        colorDictionary.put("#FFFACD", "Lemon Chiffon");
        colorDictionary.put("#FFFAF4", "Bridal Heath");
        colorDictionary.put("#FFFBDC", "Scotch Mist");
        colorDictionary.put("#FFFBF9", "Soapstone");
        colorDictionary.put("#FFFC99", "Witch Haze");
        colorDictionary.put("#FFFCEA", "Buttery White");
        colorDictionary.put("#FFFCEE", "Island Spice");
        colorDictionary.put("#FFFDD0", "Cream");
        colorDictionary.put("#FFFDE6", "Chilean Heath");
        colorDictionary.put("#FFFDE8", "Travertine");
        colorDictionary.put("#FFFDF3", "Orchid White");
        colorDictionary.put("#FFFDF4", "Quarter Pearl Lusta");
        colorDictionary.put("#FFFEE1", "Half and Half");
        colorDictionary.put("#FFFEEC", "Apricot White");
        colorDictionary.put("#FFFEF0", "Rice Cake");
        colorDictionary.put("#FFFEF6", "Black White");
        colorDictionary.put("#FFFEFD", "Romance");
        colorDictionary.put("#FFFF00", "Yellow");
        colorDictionary.put("#FFFF66", "Laser Lemon");
        colorDictionary.put("#FFFF99", "Pale Canary");
        colorDictionary.put("#FFFFB4", "Portafino");
        colorDictionary.put("#FFFFF0", "Ivory");
        colorDictionary.put("#FFFFFF", "White");


        colors.addAll(colorDictionary.keySet());
    }
}
